language: python
cache: pip

python:
    - "2.7"
    - "3.4"
    - "3.5"

sudo: false

env:
    - DJANGO=latest

matrix:
    fast_finish: true
    include:
      - { python: "3.6", env: DJANGO=latest }
      - { python: "3.6", env: TOXENV=base }
      - { python: "3.5", env: TOXENV=lint }

      - python: "3.6"
        env: TOXENV=dist
        script:
          - python setup.py bdist_wheel
          - tox --installpkg ./dist/drfserializerbuilder-*.whl
          - tox  # test sdist

    exclude:
      - { python: "2.7", env: DJANGO=latest }
      - { python: "3.4", env: DJANGO=latest }
      - { python: "3.4", env: DJANGO=latest }

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
